- name: Nginx package
  yum:
    name: nginx
    state: latest
  register: nginxinstalled

- name: Copy nginx configuration in place.
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx

- name: Nginx Service
  when: nginxinstalled|success
  service:
    name: nginx
    state: started
    enabled: yes
